version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - SALT_KEY=${SALT_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000

  frontend:
    build: ./frontend
    volumes:
      - "./frontend:/data/app"
    ports:
      - 8080:8080
